version: "3"

services:
  redis:
    image: redis:alpine

  mongo:
    image: mongo
    ports:
      - "27017:27017"

  ee_app:
    build:
        context: .
        dockerfile: Dockerfile
    ports:
      - "5000:5000"
    volumes:
      - ./data:/enzyme_evolver/database
    links:
      - redis
      - mongo
    depends_on:
      - redis
      - mongo
    environment:
      - PRODUCTION=False
      - SECRET_KEY=testing_secret_key
      - SECURITY_PASSWORD_SALT=3273928740
      - REDIS_URL=redis://redis:6379/0
      - MONGO_HOST=mongodb://mongo

    command: gunicorn -b :5000 --timeout 400 --workers 2 --access-logfile - --error-logfile - main:main_app

  worker_1:
    build:
        context: .
        dockerfile: Dockerfile
    volumes:
      - ./data:/enzyme_evolver/database
    depends_on:
      - redis
      - mongo
    links:
      - redis
      - mongo
    environment:
      - PRODUCTION=False
      - SECRET_KEY=testing_secret_key
      - SECURITY_PASSWORD_SALT=3273928740
      - REDIS_URL=redis://redis:6379/0
      - MONGO_HOST=mongodb://mongo
    command: python3 ./worker.py tasks
